services:
  database:
    image: postgres:15
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: default
      POSTGRES_DB: db_fintrack